name: 'DemosTok3n'
version: 0.0.1
description: >
  A minimal web app for the developer that doesn’t want to be confused by too
  much going on.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
  route_hierarchical: '>=0.5.0 <0.7.0'
  intl: any
  
  Tok3n_Dart:
    path: /Users/onlyangel/Documents/dev/Repositorios/Cloud_Main/Modules/default/src/Cloud_Front/Tok3n_Dart
  Tok3nAPI_Dart:
    path: /Users/onlyangel/Documents/dev/Repositorios/Cloud_Main/Modules/default/src/Cloud_Front/Tok3nAPI_Dart
transformers:
- script_inliner
#- sass:
#    style: compressed
